global CELL_EMPTY CELL_FINISH CELL_ROBOT CELL_PATH CELL_OBSTACLE
global NUMBER_OF_POSSIBLE_DIRECTIONS NUMBER_OF_POSSIBLE_MOVEMENTS
global DIRECTION_RIGHT DIRECTION_LEFT DIRECTION_UP DIRECTION_DOWN

CELL_EMPTY=0;
CELL_FINISH=-1;
CELL_ROBOT=-2;
CELL_PATH=-4;
CELL_OBSTACLE=-3;

NUMBER_OF_POSSIBLE_DIRECTIONS=4;
NUMBER_OF_POSSIBLE_MOVEMENTS=4;

DIRECTION_RIGHT=1;
DIRECTION_LEFT=2;
DIRECTION_UP=3;
DIRECTION_DOWN=4;

% global MOVEMENT_RIGHT MOVEMENT_LEFT MOVEMENT_UP MOVEMENT_DOWN
% 
% MOVEMENT_RIGHT=1;
% MOVEMENT_LEFT=2;
% MOVEMENT_UP=3;
% MOVEMENT_DOWN=4;